name: Bug Report
description: Report bugs and issues encountered in the system.
title: "[Bug] "
body:

  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      description: Provide a detailed description of the bug.
    required: true

  - type: checkboxes
    id: affected_parts
    attributes:
      label: Affected Part
      description: Select the parts of the system affected by this bug.
      options:
        - label: 🖼️ View
          value: view
        - label: 🧠 Controller
          value: controller
        - label: 🗃️ Model
          value: model
    required: true

  - type: textarea
    id: possible_solution
    attributes:
      label: Possible Solution
      description: Suggest possible solutions or workarounds for the bug.
    required: false